### ISSUE TITLE
distance_kinemat : 'break' in if statement

### ISSUE THREAD

**Issue by vc268** [PhilD001/biomechZoo#21]
Error: File: distance_kinemat.m Line: 20 Column: 2
File location: biomechZoo\Toolbox\KineMat\distance_kinemat.m

BREAK in the if statement caused the error. I tried using RETURN instead seems to work.

**Comment by PhilD001** [comment]
This function belongs to the "KineMat" toolbox of Reinschmidt and Van Den Bogert [1] and was included in biomechZoo as part of the kinematics validation. This particular function is not used by any biomechZoo function. Users are encouraged to use magnitude.m instead. Nonetheless, function has been updated in v1.7.3. 

[1] C. Reinschmidt, T. Van Den Bogert, KineMat: a MATLAB toolbox for threedimensional
kinematic analyses, 1997 . http://isbweb.org/software/movanal/
kinemat/.

**Comment by PhilD001** [comment]
function updated in v1.7.3.
