### ISSUE TITLE
xsens2zoo doesnt work

### ISSUE THREAD

**Issue by Brau20** [PhilD001/biomechZoo#24]
I am running 'xsens2zoo_example.m' Matlab 2019a, but it does not work.
Does it run properly only in Matlab 2016b version?
*********** Error message ***************
Undefined function or variable 'sheetnames'.

Error in xsens2zoo (line 43)
    sname=sheetnames(fl{i});

Error in xsens2zoo_example (line 34)
xsens2zoo(fld,ext);

**Comment by Vaibhavshahvr7** [comment]
Hello, we are looking into the issue and will be solved in few days. I will run on Matlab 2016b version after that. 
Thank you.

**Comment by Vaibhavshahvr7** [comment]
Hello, Issue is fixed in v1.7.2.
