### ISSUE TITLE
Unable to add event to all channels 

### ISSUE THREAD

**Issue by aidenhallihan** [PhilD001/biomechZoo#4]
Hello, 

I am unable to add events to all existing channels in my script. I have written the following:

**ch = 'all'; 
 
bmech_addevent(fld,ch,'max','max')                                          
bmech_addevent(fld,ch,'min','min')**

Two errors come up:

_Cell contents reference from a non-cell array object.

Error in addevent_data (line 51)
    ch = ch{i};
 
Error in bmech_addevent (line 62)
    data = addevent_data(data,ch,ename,type);_

Could you please look into this issue?

Thanks, 
Aiden

**Comment by PhilD001** [comment]
bmech_addevent and addevent_data were updated to address this bug report
