### ISSUE TITLE
Which coordinate system for the markers for soder

### ISSUE THREAD

**Issue by vigneshrk29** [PhilD001/biomechZoo#40]
Hello,

Thanks for the amazing work. I have one question regarding application of soder function? 
Do the markers need to be in the segmental reference frame? Also, should the first row of data be markers in the segment reference frame during static trial?

Thanks,
Vignesh

**Comment by PhilD001** [comment]
Hi, We don't officially support the soder applications (kinemat toolbox). We have just shown that their toolbox can work within biomechZoo. See the original authors for support http://isbweb.org/software/movanal/kinemat/
